name: 🚀 CI/CD - Java Spring Boot

on:
  push:
    branches: ['main']

env:
  DOCKER_IMAGE: ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_PROJECT }}/${{ github.event.repository.name }}:${{ github.ref_name }}_${{ github.sha }}
  DOCKER_CONTAINER: ${{ github.event.repository.name }}
  DOCKER_PLATFORM: linux/amd64

  APP_INTERNAL_PORT: ${{ vars.APP_INTERNAL_PORT || '8080' }}
  APP_EXTERNAL_PORT: ${{ secrets.APP_EXTERNAL_PORT || '8080' }}

  DEPLOY_HOST: ${{ secrets.HOST_PRODUCTION }}
  DEPLOY_USERNAME: ${{ secrets.USERNAME_PRODUCTION }}
  DEPLOY_KEY: ${{ secrets.KEY_PRODUCTION }}
  DEPLOY_PORT: ${{ secrets.PORT_PRODUCTION }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set build time
        run: echo "BUILD_TIME=$(date '+%Y-%m-%d %H:%M:%S')" >> "$GITHUB_ENV"

      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 📋 Build information
        run: |
          echo "🚀 Starting Spring Boot Build"
          echo "👤 Author: ${{ github.actor }}"
          echo "🏷️ Branch: ${{ github.ref_name }}"

      - name: 📄 Create application.properties
        run: |
          echo "📄 Creating production configuration file..."
          echo "${{ secrets.APPLICATION_PROPERTIES_PRODUCTION }}" > src/main/resources/application.properties

      - name: 🔑 Create credentials.json for Google Analytics
        run: |
          echo "🔑 Creating Google Service Account credentials..."
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > src/main/resources/credentials.json

      - name: 🔐 Registry login
        run: |
          echo "🔐 Authenticating with Docker registry..."
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: 🏗️ Build Docker image
        run: |
          echo "🏗️ Building Docker image..."
          docker build --platform ${{ env.DOCKER_PLATFORM }} -t ${{ env.DOCKER_IMAGE }} .
      
      - name: 📤 Push to registry
        run: |
          echo "📤 Pushing image to registry..."
          docker push ${{ env.DOCKER_IMAGE }}

      - name: 🎯 Build summary
        run: |
          echo "🎉 BUILD COMPLETED"
          echo "⏰ Time: ${{ env.BUILD_TIME }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set deploy time
        run: echo "DEPLOY_TIME=$(date '+%Y-%m-%d %H:%M:%S')" >> "$GITHUB_ENV"

      - name: 🚀 Deploy to server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USERNAME }}
          key: ${{ env.DEPLOY_KEY }}
          port: ${{ env.DEPLOY_PORT }}
          script: |
            echo "🚀 Starting deployment on server..."
            
            echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
            
            docker pull ${{ env.DOCKER_IMAGE }}
            
            docker rm -f ${{ env.DOCKER_CONTAINER }} || true
            
            docker run --name ${{ env.DOCKER_CONTAINER }} --restart always -dp ${{ env.APP_EXTERNAL_PORT }}:${{ env.APP_INTERNAL_PORT }} ${{ env.DOCKER_IMAGE }}
            
            echo "✅ Deployment completed"

      - name: 🎉 Deploy summary
        run: |
          echo "🎉 DEPLOYMENT COMPLETED"
          echo "👤 Deployed by: ${{ github.actor }}"
          echo "⏰ Time: ${{ env.DEPLOY_TIME }}"